# GitHub Action to run cpplint
#
name: ccplint

on: [push, pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-22.04
    name: cpplint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install cpplint
        run: |
          pip install cpplint
      - name: Run cpplint
        run: |
          cpplint --filter="-whitespace/line_length,-build/include_what_you_use,-runtime/references,-runtime/explicit,-legal/copyright,-build/header_guard" ./pybind11_protobuf/*.h
          cpplint --filter="-whitespace/line_length,-build/include_what_you_use,-runtime/references,-runtime/explicit,-legal/copyright" ./pybind11_protobuf/*.cc
          cpplint --filter="-whitespace/line_length,-build/include_what_you_use,-runtime/references,-runtime/explicit,-legal/copyright" ./pybind11_protobuf/tests/*.cc
